### ISSUE TITLE
Log only HTTP errors? Or log stack traces?

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/opencast-camera-control#34]
Right now, we log stack traces of HTTP errors. Do we want to log just the errors instead?

**Comment by tibroc** [comment]
Yes, no stacktraces needed here.

**Comment by lkiesow** [comment]
The code to change is:
https://github.com/virtUOS/opencast-camera-control/blob/61266ee69eecf7ba43cb736508e50d03c9dad521/occameracontrol/metrics.py#L69-L73

We essentially need to check for special error types to using `issubclass(exc_type, <type>)` and adjust the logging to somehing like `logger.error(…)`.
