### ISSUE TITLE
What happens if one deletes an active recording in Opencast

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/opencast-camera-control#62]
This may or may not be an edge-case where we do not yet handle changing camera positions correctly:

- Schedule an event in Opencast
- Event is being picked up by camera control
- Event starts recording and camera turns to active position
- Someone deletes the scheduled recording in Opencast
- Camera control picks up new schedule
- Recording ends

Does the camera ever turn back?
We should check this.

**Comment by janmn** [comment]
According to the debugging logs, the camera turns back the next time the calendar is updated.

**Comment by lkiesow** [comment]
Fantastic, then lets close this issue.
